secrets:
        secret_name : "twillio_creds"
        region_name : "us-west-1"
        


chatbot:
        name: "ModBot"

chatmembers:
        name: "Werewolf"
        name: "Hitman"
        name: "Civilian"


twillio:
        phone_number: "+18582982838"
        name:	"Usrnm"


